# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # 安装mkdocs
      - name: Install mkdocs
        run: python -m pip install mkdocs
        
      # 生成html
      - name: build html
        run: mkdocs build
        
      # 发布到指定目录
      - name: Deploy
        user: peaceiris/actions-gh-pages@v3
        with:
          github_token: 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
          publish_dir: ./site

